// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package line

import (
	"context"
	"yamcha/internal/config"
	"yamcha/internal/provider"
	"yamcha/pkg/repository"
	"yamcha/pkg/repository/db"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context) (repository.Repository, error) {
	configuration := config.NewConfiguration()
	gormDB, err := provider.InitGORM(configuration)
	if err != nil {
		return nil, err
	}
	repositoryRepository := db.NewRepo(gormDB)
	return repositoryRepository, nil
}
