name: deploy heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "yamcha" # Must be unique in Heroku
          heroku_email: "freedom85812@gmail.com"
          usedocker: true
          healthcheck: https://yamcha.herokuapp.com
        env:
          # PLEASE NOTE: The "HD_" will be scrapped from the variable your name by the action. 
          HD_LINECORP_PLATFORM_CHANNEL_CHANNELSECRET: ${{ secrets.LINECORP_PLATFORM_CHANNEL_CHANNELSECRET }}
          HD_LINECORP_PLATFORM_CHANNEL_CHANNELTOKEN: ${{ secrets.LINECORP_PLATFORM_CHANNEL_CHANNELTOKEN }}
          HD_LINECORP_PLATFORM_CHANNEL_SERVERURL: ${{ secrets.LINECORP_PLATFORM_CHANNEL_SERVERURL }}
          HD_MYSQL_DSN: ${{ secrets.MYSQL_DSN }}
